"""Curated prompt presets for the VoxTell widget.

Each preset maps a human-readable group name to a list of text prompts. All
strings are drawn from the curated set of labels VoxTell is known to segment well
(``voxtell_v1.1`` text embeddings), grouped by body region. Selecting a preset and
clicking "Add to prompts" appends its prompts (one per line) to the text box.
"""

# Rib bank keys look like "1st left rib" ... "12th right rib".
_ORDINALS = {1: "1st", 2: "2nd", 3: "3rd", **{n: f"{n}th" for n in range(4, 13)}}
_RIBS = [f"{_ORDINALS[n]} {side} rib" for side in ("left", "right") for n in range(1, 13)]

# Vertebra keys look like "c1 vertebra" ... "l5 vertebra".
_VERTEBRAE = (
    [f"c{i} vertebra" for i in range(1, 8)]
    + [f"t{i} vertebra" for i in range(1, 13)]
    + [f"l{i} vertebra" for i in range(1, 6)]
    + ["s1 vertebra", "sacrum"]
)

# Ordered dict (insertion order preserved) -> drives the dropdown order. Grouped
# loosely head-to-toe: organs, vessels, skeleton, muscles, neuro/head, pathology.
PRESETS = {
    "Abdominal organs": [
        "liver",
        "spleen",
        "pancreas",
        "stomach",
        "gallbladder",
        "left kidney",
        "right kidney",
        "left adrenal gland",
        "right adrenal gland",
        "duodenum",
        "small bowel",
        "colon",
        "esophagus",
        "urinary bladder",
        "aorta",
        "inferior vena cava",
    ],
    "Liver segments": [f"liver segment {i}" for i in range(1, 9)],
    "Thoracic (lungs & airways)": [
        "left lung",
        "right lung",
        "left lung upper lobe",
        "left lung lower lobe",
        "right lung upper lobe",
        "right lung middle lobe",
        "right lung lower lobe",
        "trachea",
        "bronchi",
        "thymus",
    ],
    "Cardiac (chambers & valves)": [
        "heart",
        "myocardium",
        "left atrium",
        "right atrium",
        "left ventricular cavity",
        "right ventricular cavity",
        "aortic valve",
        "mitral valve",
        "pulmonary artery tree",
        "ascending aorta",
        "aortic arch",
        "descending aorta",
    ],
    "Abdominal vasculature": [
        "abdominal aorta",
        "inferior vena cava",
        "celiac artery",
        "superior mesenteric artery",
        "inferior mesenteric artery",
        "splenic artery",
        "common hepatic artery",
        "left renal artery",
        "right renal artery",
        "left renal vein",
        "right renal vein",
        "portal veins",
        "superior mesenteric vein",
        "splenic vein",
    ],
    "Aorta segments": [
        "ascending aorta",
        "aortic arch",
        "descending aorta",
        "thoracic aorta",
        "abdominal aorta",
    ],
    "Ribs": _RIBS,
    "Vertebrae": _VERTEBRAE,
    "Bones": [
        "skull",
        "sternum",
        "sternum manubrium",
        "left clavicula",
        "right clavicula",
        "left scapula",
        "right scapula",
        "left humerus",
        "right humerus",
        "left radius",
        "right radius",
        "left ulna",
        "right ulna",
        "left hip bone",
        "right hip bone",
        "sacrum",
        "left femur",
        "right femur",
        "left patella",
        "right patella",
        "left tibia",
        "right tibia",
        "left fibula",
        "right fibula",
    ],
    "Knee": [
        "left femur",
        "right femur",
        "left tibia",
        "right tibia",
        "left patella",
        "right patella",
        "left fibula",
        "right fibula",
        "lateral meniscus",
        "medial meniscus",
        "left acl ligament",
        "right acl ligament",
        "left pcl ligament",
        "right pcl ligament",
        "left mcl ligament",
        "right mcl ligament",
        "left lcl ligament",
        "right lcl ligament",
    ],
    "Muscles": [
        f"{side} {m}"
        for m in (
            "autochthon",
            "iliopsoas",
            "gluteus maximus",
            "gluteus medius",
            "gluteus minimus",
            "rectus abdominis",
            "quadratus lumborum",
            "rectus femoris muscle",
            "vastus lateralis muscle",
            "sartorius muscle",
            "gracilis muscle",
            "biceps femoris long head muscle",
            "semitendinosus muscle",
            "gastrocnemius medial muscle",
            "soleus muscle",
        )
        for side in ("left", "right")
    ],
    "Brain structures": [
        "brain",
        "brainstem",
        "cerebellum",
        "corpus callosum",
        "left hippocampus",
        "right hippocampus",
        "left thalamus",
        "right thalamus",
        "left putamen",
        "right putamen",
        "left caudate nucleus",
        "right caudate nucleus",
        "white matter",
        "gray matter",
        "lateral ventricles",
    ],
    "Head & neck": [
        "left parotid gland",
        "right parotid gland",
        "left submandibular gland",
        "right submandibular gland",
        "thyroid gland",
        "larynx",
        "pharynx",
        "mandible",
        "oral cavity",
        "nasal cavity",
        "left eye",
        "right eye",
        "left lens",
        "right lens",
        "left optic nerve",
        "right optic nerve",
        "chiasma opticum",
        "left lacrimal gland",
        "right lacrimal gland",
        "left cochlea",
        "right cochlea",
        "left inner ear",
        "right inner ear",
        "spinal cord",
    ],
    "Brain tumor (BraTS)": [
        "edema",
        "enhancing tumor",
        "necrotic tumor",
        "non-enhancing tumor",
    ],
    # A cross-organ menu of common findings - usually you would add one or two of
    # these, not the whole list.
    "Abnormalities": [
        "tumor",
        "lesion",
        "lymph node",
        "liver lesion",
        "lung nodule",
        "kidney tumor",
        "pancreas tumor",
        "brain metastasis",
        "pleural effusion",
        "pulmonary embolism",
        "infarction",
    ],
}
